---
# tasks file for nodejs

- name: Ensure the system can use the HTTPS transport for APT
  stat:
    path: /usr/lib/apt/methods/https
  register: apt_https_transport

- name: Install HTTPS transport for APT
  apt:
    pkg: apt-transport-https
    state: installed
  when: not apt_https_transport.stat.exists

- name: Import the NodeSource GPG key into apt
  apt_key:
    url: http://deb.nodesource.com/gpgkey/nodesource.gpg.key
    state: present

- name: Check if nodejs_version is 10.x or higher
  set_fact: nodejs_debian_repo_version="10.x"
  when: "nodejs_version | version_compare('10.0', operator='>=')"

- name: Add NodeSource deb repository
  apt_repository:
    repo: "{{ item }}"
    state: present
  with_items:
    - 'deb https://deb.nodesource.com/node_{{ nodejs_debian_repo_version }} {{ ansible_distribution_release }} main'
    - 'deb-src https://deb.nodesource.com/node_{{ nodejs_debian_repo_version }} {{ ansible_distribution_release }} main'

- name: Install Node.js
  apt:
    name: "nodejs={{ nodejs_version|regex_replace('x', '') }}*"
    state: present
    update_cache: yes

- name: Ensure npm global packages are at the latest release.
  npm:
    name: "{{ item.name }}"
    version: "{{ item.version | default('') }}"
    global: yes
    state: latest
  with_items: "{{ nodejs_npm_global_packages }}"